
import traceback
try:
    print('es klappt!')
except:
    traceback.print_exc()
